// Original creature-collector names. The array order matches each set's
// printed card order in gameData.js; gameplay effects remain authoritative in
// engineCards.js. Keeping identities separate makes the art pipeline and the
// review gallery deterministic without coupling gameData back to the engine.
const NAMES_BY_SET = {
  corner: [
    "Coinbud",
    "Pennigeon",
    "Duplop",
    "Novabeet",
    "Bankslime",
    "Luckfox",
    "Echaccoon",
    "Questmunch",
    "Packross",
    "Echowl",
    "Setinel",
    "Echuneko",
  ],
  circuit: [
    "Marklet",
    "Bountibot",
    "Cresthopper",
    "Glyphguard",
    "Coincrawler",
    "Arcshade",
    "Signaskate",
    "Questchrome",
    "Reverbogre",
    "Bluebit",
    "Echoboard",
    "Zeraph",
  ],
  frontier: [
    "Scrapactus",
    "Salvatort",
    "Accelmoth",
    "Mystumble",
    "Setmole",
    "Coinbison",
    "Salvoon",
    "Mystrail",
    "Goldgorge",
    "Griffgold",
    "Reclaimotive",
    "Salvitan",
  ],
  abyss: [
    "Mimipolyp",
    "Coinnow",
    "Douburchin",
    "Sigilshell",
    "Firstfin",
    "Twinjelly",
    "Treasurekelp",
    "Packray",
    "Questcrab",
    "Echowhale",
    "Mystivora",
    "Mimistar",
  ],
  crown: [
    "Resonash",
    "Echandle",
    "Gildrat",
    "Bellcho",
    "Sigilhound",
    "Questhorn",
    "Pacturion",
    "Heraldthorn",
    "Coincrow",
    "Regalynx",
    "Locklure",
    "Coronova",
  ],
  verdant: [
    "Tripmoss",
    "Coinfern",
    "Mergeimp",
    "Fusihare",
    "Recyclen",
    "Liftvine",
    "Orchiforge",
    "Catalystag",
    "Boiloreverb",
    "Crosscanopy",
    "Fusigrove",
    "Heartmerge",
  ],
  polar: [
    "Mutemouse",
    "Shiftguin",
    "Cryoworm",
    "Coinquill",
    "Sigilyak",
    "Bluffox",
    "Glyphcurator",
    "Arctatlas",
    "Questora",
    "Trueglacier",
    "Reflectome",
    "Absolumute",
  ],
  ember: [
    "Cracktoad",
    "Coinswitch",
    "Coalcrack",
    "Riftpup",
    "Sootroc",
    "Wildductor",
    "Riftation",
    "Sigilnomad",
    "Magmaforge",
    "Riftclipse",
    "Cinderscrap",
    "Solfract",
  ],
  cloud: [
    "Coinfin",
    "Parcelglyph",
    "Bellspread",
    "Foilmonk",
    "Catalitea",
    "Foilvan",
    "Questsoon",
    "Salvimbus",
    "Aucsigil",
    "Mystipalace",
    "Swiftstar",
    "Catalyra",
  ],
  glass: [
    "Echolisk",
    "Mirrordub",
    "Novajackal",
    "Questdune",
    "Gradestorm",
    "Casecho",
    "Diamondreverb",
    "Questphinx",
    "Choicepolis",
    "Sunshimmer",
    "Mystihalo",
    "Bluprintix",
  ],
  harbor: [
    "Lastcrab",
    "Scraptide",
    "Questferry",
    "Futurwake",
    "Anchorscrap",
    "Relaykraken",
    "Seeklight",
    "Twinmoon",
    "Accelwreck",
    "Salvboard",
    "Resofleet",
    "Portalink",
  ],
  orchard: [
    "Questworm",
    "Choicopper",
    "Graftquest",
    "Coincider",
    "Quickron",
    "Questpear",
    "Lingermet",
    "Packseason",
    "Glyphcrow",
    "Returnroot",
    "Consolapple",
    "Autoharvest",
  ],
  hollow: [
    "Resonewt",
    "Coinbasalt",
    "Echovore",
    "Gemram",
    "Encorekeep",
    "Meteormint",
    "Pressurite",
    "Starcoin",
    "Memorymount",
    "Firstone",
    "Rootpack",
    "Heartforge",
  ],
  prism: [
    "Questfinch",
    "Shimmermeleon",
    "Gleamint",
    "Sigilmoth",
    "Mutekoi",
    "Halolion",
    "Questserpent",
    "Peacoreverb",
    "Prismorph",
    "Mergebeast",
    "Catalyhab",
    "Omniecho",
  ],
  signal: [
    "Bluffshrimp",
    "Scrapeel",
    "Acceloray",
    "Mystinaut",
    "Salvabuoy",
    "Seekwhale",
    "Reclaimsos",
    "Coincast",
    "Setsignal",
    "Suncoin",
    "Omniocean",
    "Recyclora",
  ],
  observatory: [
    "Questcap",
    "Truescope",
    "Coincomet",
    "Halomorph",
    "Questhound",
    "Lunaglyph",
    "Firstseer",
    "Lensreverb",
    "Dawnsigil",
    "Mimiceye",
    "Questclipse",
    "Orbitmark",
  ],
  foundry: [
    "Rivverb",
    "Packladle",
    "Foilpress",
    "Coinwelder",
    "Bellpack",
    "Scrapanvil",
    "Riftforge",
    "Coincrucible",
    "Riftprint",
    "Questhammer",
    "Scrapline",
    "Twinforge",
  ],
  apocalypse: [
    "Scrapcup",
    "Coinhalo",
    "Bankmap",
    "Tickscrap",
    "Luckruin",
    "Accelence",
    "Coinrise",
    "Rarehouse",
    "Epicwindow",
    "Foldouble",
    "Songbank",
    "Peacescrap",
  ],
  lastlight: [
    "Matchacho",
    "Nightecho",
    "Coinlantern",
    "Sparksigil",
    "Chromaglow",
    "Solarcatalyst",
    "Dawnrift",
    "Luminmerge",
    "Horizonhoard",
    "Queststar",
    "Shadowreclaim",
    "Luxquest",
  ],
  unwritten: [
    "Marginmint",
    "Lingertale",
    "Futureword",
    "Scrappage",
    "Dawnfolio",
    "Erasemint",
    "Mergeglyph",
    "Seekmark",
    "Echochapter",
    "Riftquill",
    "Handscript",
    "Nameling",
  ],
};

const FLAVOR_BY_VIBE = {
  cash: "Golden tokens tumble from every victory.",
  duplicate: "A familiar face is never wasted.",
  new: "It spots a first encounter before anyone else.",
  threshold: "It counts every step toward the next surprise.",
  pack: "One more companion always fits.",
  rare: "Rare light draws out its strongest instinct.",
  set: "A finished collection wakes its hidden power.",
  echo: "Its power returns on a bright second beat.",
  mark: "A glowing crest chooses what happens next.",
  salvage: "It turns every spare piece into a fresh mystery.",
  discover: "Three shining paths open wherever it points.",
  mimic: "One glance is enough to learn a new shape.",
  mystery: "Sealed surprises gather wherever it wanders.",
  fusion: "Matching sparks combine beneath its careful gaze.",
  catalyst: "One change leaps eagerly to the next.",
  transmute: "Color and rarity shift at its touch.",
  signal: "It hears the truth hiding inside a false signal.",
  fracture: "A harmless rift spills another pack into play.",
  foil: "Rainbow light clings to every motion.",
  grade: "Its polish reveals a brighter hidden form.",
  relay: "Its spark never stops with the first friend.",
  autopilot: "It always knows the brightest choice.",
  encore: "The final card is only another beginning.",
  rewrite: "Its living ink can begin the whole story again.",
};

const VIBES_BY_SET = {
  corner: ["cash", "cash", "duplicate", "new", "threshold", "cash", "echo", "threshold", "pack", "echo", "set", "echo"],
  circuit: ["mark", "cash", "mark", "mark", "cash", "mark", "mark", "discover", "echo", "cash", "echo", "mark"],
  frontier: ["salvage", "threshold", "salvage", "mystery", "salvage", "cash", "salvage", "cash", "mystery", "rare", "salvage", "salvage"],
  abyss: ["mimic", "cash", "duplicate", "mimic", "cash", "mimic", "rare", "pack", "discover", "echo", "cash", "mimic"],
  crown: ["echo", "echo", "cash", "echo", "cash", "discover", "cash", "mark", "cash", "set", "cash", "echo"],
  verdant: ["discover", "cash", "cash", "fusion", "salvage", "fusion", "fusion", "catalyst", "echo", "fusion", "discover", "fusion"],
  polar: ["transmute", "transmute", "transmute", "cash", "transmute", "signal", "transmute", "transmute", "discover", "signal", "transmute", "transmute"],
  ember: ["fracture", "cash", "cash", "fracture", "cash", "fracture", "fracture", "mark", "cash", "mark", "salvage", "fracture"],
  cloud: ["cash", "mark", "mark", "cash", "catalyst", "foil", "discover", "salvage", "mark", "cash", "threshold", "catalyst"],
  glass: ["echo", "duplicate", "new", "discover", "grade", "cash", "echo", "discover", "discover", "echo", "echo", "mimic"],
  harbor: ["cash", "threshold", "discover", "mystery", "salvage", "relay", "mystery", "mystery", "salvage", "salvage", "echo", "relay"],
  orchard: ["discover", "discover", "discover", "cash", "threshold", "discover", "discover", "pack", "mark", "discover", "discover", "autopilot"],
  hollow: ["echo", "cash", "echo", "cash", "encore", "cash", "fusion", "cash", "echo", "cash", "pack", "salvage"],
  prism: ["discover", "foil", "cash", "echo", "echo", "mark", "discover", "echo", "transmute", "echo", "catalyst", "echo"],
  signal: ["discover", "salvage", "salvage", "threshold", "salvage", "mystery", "salvage", "cash", "salvage", "cash", "discover", "salvage"],
  observatory: ["discover", "signal", "cash", "transmute", "discover", "mark", "discover", "echo", "mark", "mimic", "discover", "mark"],
  foundry: ["echo", "pack", "foil", "cash", "pack", "salvage", "fusion", "cash", "fracture", "discover", "salvage", "fusion"],
  apocalypse: ["salvage", "cash", "threshold", "salvage", "cash", "salvage", "cash", "mystery", "cash", "duplicate", "cash", "salvage"],
  lastlight: ["echo", "echo", "cash", "mark", "transmute", "catalyst", "fracture", "fusion", "mystery", "discover", "salvage", "discover"],
  unwritten: ["new", "discover", "mystery", "salvage", "pack", "cash", "fusion", "mystery", "echo", "discover", "relay", "rewrite"],
};

export const CARD_IDENTITIES = Object.fromEntries(
  Object.entries(NAMES_BY_SET).flatMap(([setId, names]) => names.map((name, index) => [
    `${setId}-${String(index + 1).padStart(2, "0")}`,
    {
      name,
      flavor: FLAVOR_BY_VIBE[VIBES_BY_SET[setId][index]],
      vibe: VIBES_BY_SET[setId][index],
    },
  ])),
);

export function getCardIdentity(cardId) {
  return CARD_IDENTITIES[cardId] || null;
}
