// PixelLab portraits from cards outside the selected core are reassigned to
// core cards that did not yet have generated art. Card names and gameplay
// rules remain those of the selected core card; only the portrait identity is
// reused. Values are the donor live-card ids from the pre-core print lines.
export const CORE_ART_TRANSFERS = {
  "marquee-19": "marquee-47",
  "marquee-22": "marquee-07",
  "marquee-23": "lastarchive-44",
  "marquee-28": "mirrorfield-43",
  "marquee-36": "marquee-08",
  "marquee-41": "lastarchive-33",

  "tideworks-01": "tideworks-39",
  "tideworks-02": "tideworks-38",
  "tideworks-07": "tideworks-47",
  "tideworks-09": "lastarchive-43",
  "tideworks-11": "lastarchive-35",
  "tideworks-15": "lastarchive-40",
  "tideworks-19": "lastarchive-32",
  "tideworks-35": "tideworks-23",
  "tideworks-36": "tideworks-27",
  "tideworks-41": "forgeline-32",

  "forgeline-01": "lastarchive-37",
  "forgeline-02": "lastarchive-41",
  "forgeline-03": "forgeline-30",
  "forgeline-04": "lastarchive-42",
  "forgeline-05": "forgeline-46",
  "forgeline-06": "forgeline-37",
  "forgeline-07": "lastarchive-30",
  "forgeline-08": "mirrorfield-47",
  "forgeline-09": "forgeline-36",
  "forgeline-10": "mirrorfield-46",
  "forgeline-11": "marquee-11",
  "forgeline-12": "lastarchive-45",
  "forgeline-14": "tideworks-40",
  "forgeline-16": "forgeline-33",
  "forgeline-17": "lastarchive-46",
  "forgeline-19": "lastarchive-26",
  "forgeline-21": "mirrorfield-42",
  "forgeline-22": "lastarchive-39",
  "forgeline-23": "marquee-31",

  "mirrorfield-04": "marquee-45",
  "mirrorfield-05": "lastarchive-25",
  "mirrorfield-06": "marquee-46",
  "mirrorfield-13": "lastarchive-27",
  "mirrorfield-14": "mirrorfield-41",
  "mirrorfield-18": "marquee-16",
  "mirrorfield-22": "lastarchive-11",
  "mirrorfield-24": "lastarchive-23",
  "mirrorfield-26": "marquee-06",
  "mirrorfield-28": "mirrorfield-37",

  "lastarchive-06": "lastarchive-36",
  "lastarchive-13": "marquee-04",
};
