import { MECHANICS } from "./mechanicsCatalog.js";

const MINI_SET_DETAILS = {
  reveal: {
    title: "Common Flood",
    archetype: "Volume / automatic opening",
    thesis: "Lock the pack to Commons, make each reveal pay, then turn the first flip into a growing automatic chain.",
    loop: [
      "Locklure makes the pack Common-only while adding more Commons during the reveal.",
      "Packross and Bellpack widen the opening; Firstseer turns the first click into the whole sequence.",
      "Coinbud, Pennigeon, and Coinhalo pay on every Common while Encorekeep can restart the final beat.",
    ],
    strength: "Extremely legible and explosive once all three Common payoffs are seated.",
    watchout: "The Common lock gives up natural high-rarity pulls, so this is an economy engine rather than a collection-quality engine.",
    caseOrder: ["marquee-35", "marquee-43", "marquee-01", "marquee-02", "tideworks-37", "forgeline-27"],
    cards: [
      { id: "marquee-35", role: "ENGINE", note: "Locks pulls to Common and can keep adding cards to the same opening." },
      { id: "marquee-43", role: "AUTOMATION", note: "One first reveal resolves the rest of the pack." },
      { id: "marquee-01", role: "PAYOFF", note: "Turns every Common into sell-value cash." },
      { id: "marquee-02", role: "PAYOFF", note: "Adds a reliable flat reward to every Common." },
      { id: "tideworks-37", role: "FINISHER", note: "Makes each Common reveal pay at endgame scale." },
      { id: "forgeline-27", role: "EXTENDER", note: "The final reveal can add three more cards and restart the loop." },
      { id: "marquee-09", role: "FLEX / WIDTH", note: "Adds one card to every opening." },
      { id: "forgeline-40", role: "FLEX / WIDTH", note: "Adds four cards when raw reveal volume matters more than Encore." },
    ],
  },
  echo: {
    title: "Afterimage Ladder",
    archetype: "Repeat triggers / pack growth",
    thesis: "Guarantee repeat reveals on valuable cards, let Echo repeat itself, and convert every repeat into more cards.",
    loop: [
      "Omniecho gives every card an Echo floor while the rare-focused sources push premium pulls past 100%.",
      "Reverbogre can chain each Echo and Resonance adds another guaranteed repeat to the next event.",
      "Echowl converts the repeated trigger into another card, feeding the reveal engine again.",
    ],
    strength: "Chance above 100% becomes additional guaranteed Echoes, so none of the stacked sources are wasted.",
    watchout: "This package needs a good reveal payoff beside it; Echo multiplies what a card already does.",
    caseOrder: ["mirrorfield-48", "lastarchive-24", "marquee-20", "marquee-10", "tideworks-22", "forgeline-23"],
    cards: [
      { id: "mirrorfield-48", role: "ENGINE", note: "Gives every card a universal +50% Echo floor." },
      { id: "lastarchive-24", role: "SCALER", note: "Rare-or-better pulls gain a full additional Echo." },
      { id: "marquee-20", role: "CHAIN", note: "Each Echo can repeat again." },
      { id: "marquee-10", role: "PAYOFF", note: "Every Echo physically grows the current pack." },
      { id: "tideworks-22", role: "CHARGE", note: "Opening packs can bank Resonance for another Echo." },
      { id: "forgeline-23", role: "CHARGE", note: "Common reveals can bank Resonance while premium cards carry the main loop." },
      { id: "marquee-23", role: "FLEX / RARE", note: "A second rare-focused source for a premium-pull version." },
      { id: "marquee-42", role: "FLEX / MARK", note: "Turns a Mark board into a simultaneous Echo wave." },
    ],
  },
  mark: {
    title: "Constellation Board",
    archetype: "Visible setup / marked payoffs",
    thesis: "Guarantee a visible Mark, bias it toward the best card, spread and stack it, then cash the marked reveal into money, Discover, and Echo.",
    loop: [
      "Zeraph guarantees the first Mark and Cresthopper places it on the pack’s highest-rarity target.",
      "Glyphguard spreads the property while Heraldthorn lets repeat applications stack.",
      "Bountibot, Questchrome, and Lunaglyph turn each marked reveal into three different payoff lanes.",
    ],
    strength: "The player can see the setup before revealing and choose the exact moment to cash it in.",
    watchout: "A Mark without a payoff is only information; keep at least two marked-reveal cards in the active six.",
    caseOrder: ["marquee-34", "marquee-14", "marquee-15", "marquee-30", "marquee-19", "marquee-42"],
    cards: [
      { id: "marquee-34", role: "ENGINE", note: "Guarantees a Marked card in every pack." },
      { id: "marquee-14", role: "TARGETING", note: "Biases the Mark toward the highest-rarity pull." },
      { id: "marquee-15", role: "SPREAD", note: "A revealed Mark can move onto another face-down card." },
      { id: "marquee-30", role: "STACKING", note: "Allows multiple Marks to collect on the same target." },
      { id: "marquee-19", role: "VALUE", note: "Marked reveals become Discover chances." },
      { id: "marquee-42", role: "FINISHER", note: "One marked reveal Echoes the entire marked board." },
      { id: "marquee-12", role: "FLEX / SOURCE", note: "A lower-rarity Mark source when Zeraph is unavailable." },
      { id: "marquee-13", role: "FLEX / CASH", note: "A simple cash payoff for each Marked reveal." },
    ],
  },
  salvage: {
    title: "Mystery Flywheel",
    archetype: "Duplicate conversion / recursive packs",
    thesis: "Turn duplicate sales into Mystery Packs, enlarge and improve those packs, then use their openings to charge the next Salvage.",
    loop: [
      "Scrapactus starts the engine whenever duplicates sell; Acceloray banks an extra Salvage on the sale action.",
      "Salvoon and Twinmoon multiply the number of Mystery cards produced while Rarehouse raises their quality.",
      "Reclaimotive, Accelence, and Mystinaut let Mystery openings charge or repeat the next cycle.",
    ],
    strength: "Converts the least exciting resource—duplicates—into new-card velocity and future-set access.",
    watchout: "It needs duplicate volume before it becomes self-sustaining; early collection progress can make the first ignition slow.",
    caseOrder: ["tideworks-01", "tideworks-25", "tideworks-07", "tideworks-19", "tideworks-11", "tideworks-41"],
    cards: [
      { id: "tideworks-01", role: "ENGINE", note: "Every duplicate sold is an independent Salvage roll." },
      { id: "tideworks-25", role: "CHARGE", note: "Selling the pile guarantees Acceleration for the next Salvage." },
      { id: "tideworks-07", role: "MULTIPLIER", note: "Each Salvage opens another Mystery Pack." },
      { id: "tideworks-19", role: "WIDTH", note: "Each Mystery Pack contains four more cards." },
      { id: "tideworks-11", role: "REPEAT", note: "Salvage can immediately run again." },
      { id: "tideworks-41", role: "LOOP", note: "Mystery openings can bank another Acceleration." },
      { id: "tideworks-26", role: "FLEX / LOOP", note: "Every sixth Mystery Pack forces another Salvage." },
      { id: "tideworks-43", role: "FLEX / QUALITY", note: "Trades some loop speed for Rare-or-better Mystery bias." },
    ],
  },
  mimic: {
    title: "Marked Reflection",
    archetype: "Copy quality / duplicate value",
    thesis: "Mark the best pull, make Mimic prefer it, copy it twice, then profit when those copied identities become valuable duplicates.",
    loop: [
      "Zeraph exposes a premium target before reveal and Mimistar copies a face-down card each pack.",
      "Sigilshell and Mimipolyp steer the copy toward the Marked, highest-rarity card; Twinjelly can make a second copy.",
      "Lunaglyph repeats the marked copies while Casecho pays when the copied identity is also displayed.",
    ],
    strength: "Turns one lucky premium pull into a visible, repeatable pack plan.",
    watchout: "Mimic creates more copies, so its binder value falls unless the duplicate and Echo payoffs are online.",
    caseOrder: ["mirrorfield-31", "marquee-34", "mirrorfield-04", "mirrorfield-06", "marquee-42", "lastarchive-06"],
    cards: [
      { id: "mirrorfield-31", role: "ENGINE", note: "Creates one Mimic copy before each pack is revealed." },
      { id: "marquee-34", role: "SETUP", note: "Guarantees a visible Mark target for the copy bias." },
      { id: "mirrorfield-04", role: "TARGETING", note: "Makes copies prefer the Marked card." },
      { id: "mirrorfield-06", role: "MULTIPLIER", note: "Mimic can copy a second target." },
      { id: "marquee-42", role: "PAYOFF", note: "Echoes the marked cards after the copies settle." },
      { id: "lastarchive-06", role: "CASH OUT", note: "Pays when a duplicated displayed identity is revealed." },
      { id: "mirrorfield-01", role: "FLEX / TARGET", note: "Targets the highest rarity when no Mark package is available." },
      { id: "tideworks-45", role: "FLEX / DUPES", note: "Raises duplicate density for a Casecho-first version." },
    ],
  },
  fusion: {
    title: "Golden Assembly",
    archetype: "Rarity climb / recursive Fusion",
    thesis: "Make pairs easier to form, let isolated cards climb, deepen every merge, then repeat the full chain with foil and Echo upside.",
    loop: [
      "Heartmerge supplies the pair rule; Crosscanopy and Orchiforge loosen the pairing requirements.",
      "Fusihare and Catalystag increase how far each successful merge climbs.",
      "Boiloreverb and Foilpress improve the result before Twinforge runs the entire chain again.",
    ],
    strength: "Every support attacks a different bottleneck: pair availability, depth, result quality, or recursion.",
    watchout: "Fusion consumes card count. Without wide packs or Fracture, the chain can run out of raw material.",
    caseOrder: ["forgeline-31", "forgeline-10", "forgeline-07", "forgeline-04", "forgeline-08", "forgeline-47"],
    cards: [
      { id: "forgeline-31", role: "ENGINE", note: "Activates same-rarity pairing and immediate upgraded reveals." },
      { id: "forgeline-10", role: "PAIRING", note: "Allows adjacent rarities to form a pair." },
      { id: "forgeline-07", role: "PAIRING", note: "Lets an unpaired card climb by itself." },
      { id: "forgeline-04", role: "DEPTH", note: "Adds one rarity step to the Fusion ceiling." },
      { id: "forgeline-08", role: "CHARGE", note: "Fusions can bank a Catalyst boon for another rarity step." },
      { id: "forgeline-47", role: "FINISHER", note: "Runs the full Fusion resolution a second time." },
      { id: "forgeline-09", role: "FLEX / ECHO", note: "Gives each fused result another chance to retrigger." },
      { id: "forgeline-38", role: "FLEX / FOIL", note: "Turns half of fused results into foil cards." },
    ],
  },
  transmute: {
    title: "Rarity Slingshot",
    archetype: "Targeted rarity movement",
    thesis: "Stack enough Transmute chance to fire consistently, aim it at Marked cards, climb multiple steps, and pay off each transformed reveal.",
    loop: [
      "Absolumute and Halomorph combine into reliable Transmute checks on reveals.",
      "Glyphcurator points those checks at Marked cards while Cryoworm and Prismorph increase upward distance.",
      "Reflectome adds another target and Coincrucible converts every successful transformed reveal into premium cash.",
    ],
    strength: "The entire eight-card package is mechanically direct; every slot either creates, aims, deepens, or rewards Transmute.",
    watchout: "Transmute needs unrevealed targets, so instant whole-pack reveal effects can erase its decision window.",
    caseOrder: ["mirrorfield-34", "marquee-39", "mirrorfield-18", "mirrorfield-45", "mirrorfield-22", "forgeline-43"],
    cards: [
      { id: "mirrorfield-34", role: "ENGINE", note: "Provides the core +50% Transmute chance." },
      { id: "marquee-39", role: "SCALER", note: "Adds another +60% so overflow can support repeated checks." },
      { id: "mirrorfield-18", role: "TARGETING", note: "Points Transmute at visible Marked cards." },
      { id: "mirrorfield-45", role: "DEPTH", note: "Adds two upward rarity steps." },
      { id: "mirrorfield-22", role: "WIDTH", note: "Epic reveals bank Reflection for another affected card." },
      { id: "forgeline-43", role: "PAYOFF", note: "Transmuted reveals pay 25× sell value." },
      { id: "mirrorfield-13", role: "FLEX / CHANCE", note: "Commons add another Transmute chance pulse." },
      { id: "mirrorfield-14", role: "FLEX / DEPTH", note: "A cheaper one-step depth option." },
    ],
  },
  fracture: {
    title: "Rift Cascade",
    archetype: "Pack multiplication / cross-engine spill",
    thesis: "Push Fracture near certainty, diversify the spilled pack, then turn every spill into Marks, cash, Salvage, and a stronger Fusion.",
    loop: [
      "Dawnrift and Cracktoad supply 48% combined Fracture chance on every pack.",
      "Wildductor changes the source set and Sigilnomad marks most cards that spill into the reveal.",
      "Coalcrack pays immediately while Riftclipse, Cinderscrap, and Riftforge seed three follow-up engines.",
    ],
    strength: "This is a complete eight-card mechanic package with a clear source, modifiers, and several visible payoffs.",
    watchout: "Fracture grows opening boards rapidly; it is strongest when reveal automation or the 100-card FINISH failsafe is available.",
    caseOrder: ["lastarchive-29", "forgeline-12", "forgeline-17", "forgeline-19", "forgeline-22", "forgeline-42"],
    cards: [
      { id: "lastarchive-29", role: "ENGINE", note: "Adds the largest live Fracture chance source." },
      { id: "forgeline-12", role: "SCALER", note: "Adds another independent Fracture chance." },
      { id: "forgeline-17", role: "VARIANCE", note: "Spills from any unlocked set instead of only the current one." },
      { id: "forgeline-19", role: "PROPERTY", note: "Makes most spilled cards arrive Marked." },
      { id: "forgeline-22", role: "PAYOFF", note: "Each Fracture can immediately Salvage." },
      { id: "forgeline-42", role: "BRIDGE", note: "Each Fracture deepens the next Fusion." },
      { id: "forgeline-14", role: "FLEX / CASH", note: "Pays two pack prices every time a rift opens." },
      { id: "forgeline-21", role: "FLEX / MARK", note: "Each Fracture banks Insight for a wider Mark setup." },
    ],
  },
  catalyst: {
    title: "Property Web",
    archetype: "Mark + Mimic + Transmute spread",
    thesis: "Land one valuable property on a face-down card, spread it through the remaining pack, then cash out a board of marked or transformed copies.",
    loop: [
      "Zeraph, Mimistar, and Absolumute provide the three properties Catalyst is designed to copy.",
      "A Catalyst spread source should propagate those properties; Glyphcurator and Sigilnomad improve the resulting targets.",
      "Glyphguard and Lunaglyph keep the Mark branch spreading and then Echo the completed property web.",
    ],
    strength: "Catalyst is the natural bridge between three otherwise separate pack-manipulation engines.",
    watchout: "The live 98-card pool has no card with catalystChance. Catalystag grants the Fusion boon named Catalyst, not the property-spread mechanic.",
    flag: "MISSING LIVE SIGNATURE",
    caseOrder: ["marquee-34", "mirrorfield-31", "mirrorfield-34", "forgeline-08", "marquee-15", "marquee-42"],
    cards: [
      { id: "marquee-34", role: "PROPERTY / MARK", note: "Creates a guaranteed Mark for the intended spread check." },
      { id: "mirrorfield-31", role: "PROPERTY / COPY", note: "Creates a Mimic copy for the intended spread check." },
      { id: "mirrorfield-34", role: "PROPERTY / SHIFT", note: "Creates Transmuted targets for the intended spread check." },
      { id: "forgeline-08", role: "NAME COLLISION", note: "Grants the Fusion boon called Catalyst; it is not a property-spread source." },
      { id: "marquee-15", role: "MARK SPREAD", note: "Shows the Mark-only version of the intended spread behavior." },
      { id: "marquee-42", role: "PAYOFF", note: "Echoes the final board of Marked cards." },
      { id: "forgeline-19", role: "FLEX / MARK", note: "Fracture creates a large batch of Marked property carriers." },
      { id: "mirrorfield-18", role: "FLEX / TARGET", note: "Transmute prefers the Marked cards created by the web." },
    ],
  },
  blueprint: {
    title: "Double Keystone",
    archetype: "Slot-one duplication",
    thesis: "Put the strongest scalable rule in slot one, copy it with Blueprint, then spend the remaining four slots on the engine that benefits most from doubling.",
    loop: [
      "Choose the slot-one rule: Fracture chance, Echo chance, pack width, Mystery width, or a triggered payoff.",
      "Blueprint in slot two should become an exact second copy of that rule with no selection UI.",
      "The remaining cards complete whichever doubled engine was chosen; swap the slot-one target to change builds.",
    ],
    strength: "One signature becomes a universal second copy of the best card you own and makes case order a strategic decision.",
    watchout: "The intended Blueprint slot is represented by Truescope, but its current live text triggers the card to its left instead of copying slot one.",
    flag: "SIGNATURE TEXT MISMATCH",
    caseOrder: ["lastarchive-29", "marquee-37", "tideworks-07", "tideworks-19", "lastarchive-24", "forgeline-40"],
    cards: [
      { id: "lastarchive-29", role: "TARGET / FRACTURE", note: "A doubled +40% Fracture source demonstrates the cleanest Blueprint ceiling." },
      { id: "marquee-37", role: "MISSING BLUEPRINT", note: "Pinned as the intended Blueprint card, but currently prints a left-trigger Mark effect." },
      { id: "tideworks-07", role: "TARGET / SALVAGE", note: "Doubling this makes each Salvage open two additional Mystery Packs." },
      { id: "tideworks-19", role: "TARGET / WIDTH", note: "Doubling this adds eight cards to every Mystery Pack." },
      { id: "lastarchive-24", role: "TARGET / ECHO", note: "Doubling this pushes rare Echo far beyond one repeat." },
      { id: "forgeline-40", role: "TARGET / PACKS", note: "Doubling this adds eight cards to every normal pack." },
      { id: "marquee-41", role: "FLEX / DISCOVER", note: "A copied pack-open trigger would produce two Discovers per pack." },
      { id: "forgeline-39", role: "FLEX / CASH", note: "A copied fused-reveal payoff would double premium cash output." },
    ],
  },
  relay: {
    title: "Rightward Circuit",
    archetype: "Positional trigger chain",
    thesis: "Place frequent triggers on the left and expensive payoffs on their right so one natural event forces a second card to fire for free.",
    loop: [
      "Coinbud supplies a frequent left-edge trigger; Questcap rewards the fact that its left neighbor fired.",
      "Portalink turns every trigger into a spark that seeks the next trigger card to the right.",
      "Scrapanvil, Accelence, and Rootpack form a high-value Salvage-to-Mystery-to-pack chain when forced in order.",
    ],
    strength: "Relay changes card order from presentation into engine logic and can fire payoffs without their normal condition.",
    watchout: "The live pool has no relayDepth card, so each natural trigger gets one Relay jump; ordering mistakes waste the spark.",
    caseOrder: ["marquee-01", "marquee-36", "forgeline-41", "tideworks-41", "forgeline-35", "tideworks-34"],
    cards: [
      { id: "marquee-01", role: "SLOT 1 / PULSE", note: "Common reveals create a frequent left-edge trigger." },
      { id: "marquee-36", role: "SLOT 2 / BRIDGE", note: "Discovers when its left neighbor triggers." },
      { id: "forgeline-41", role: "SLOT 3 / PAYOFF", note: "A forced trigger Salvages without waiting for Fusion." },
      { id: "tideworks-41", role: "SLOT 4 / CHARGE", note: "A forced trigger banks Acceleration." },
      { id: "forgeline-35", role: "SLOT 5 / PACK", note: "A forced trigger awards another loose pack." },
      { id: "tideworks-34", role: "ENGINE", note: "Activates the rightward Relay rule globally." },
      { id: "marquee-37", role: "FLEX / REVERSE", note: "Marked reveals can kick the card immediately to the left." },
      { id: "marquee-41", role: "FLEX / SOURCE", note: "A pack-open trigger can begin a slower but guaranteed circuit." },
    ],
  },
  discover: {
    title: "Boon Toolbox",
    archetype: "Choice density / stacked upgrades",
    thesis: "Trigger Discover from several natural play patterns, widen and enhance the offer, then stack exactly the boons the next engine event needs.",
    loop: [
      "Questhound guarantees an offer on pack open while Mark, Rare, duplicate, and Fusion cards add contextual offers.",
      "Choicopper keeps an extra option and Omniocean exposes the full five-boon pool.",
      "Luxquest enhances every choice before the player stacks it for Mark, Echo, Fusion, Transmute, or Salvage.",
    ],
    strength: "It is the most flexible support package because the player chooses which primary mechanic receives the boost.",
    watchout: "Discover is not a standalone payoff; stacked boons do nothing until their matching mechanic fires.",
    caseOrder: ["marquee-41", "marquee-19", "marquee-28", "lastarchive-13", "tideworks-35", "lastarchive-47"],
    cards: [
      { id: "marquee-41", role: "ENGINE", note: "Every opened pack guarantees a Discover." },
      { id: "marquee-19", role: "MARK SOURCE", note: "Marked reveals add more offers." },
      { id: "marquee-28", role: "RARITY SOURCE", note: "Rare-or-better reveals add more offers." },
      { id: "lastarchive-13", role: "KEEP", note: "Each Discover keeps one additional option." },
      { id: "tideworks-35", role: "CHOICE", note: "Shows all five boons in every offer." },
      { id: "lastarchive-47", role: "QUALITY", note: "Enhances every Discover option." },
      { id: "forgeline-01", role: "FLEX / DUPES", note: "Three duplicates in a row create an offer." },
      { id: "forgeline-11", role: "FLEX / FUSION", note: "Every twelve Fusions create an offer." },
    ],
  },
  autopilot: {
    title: "Hands-Free Boons",
    archetype: "Automatic enhanced Discover",
    thesis: "Flood the run with Discover triggers and let Autopilot convert every interruption into an immediate enhanced boon.",
    loop: [
      "Questhound begins with a Discover every pack; Mark, Rare, duplicate, and Fusion triggers add more offers.",
      "Autoharvest skips the choice screen, selects automatically, and enhances the selected boon.",
      "Choicopper and Omniocean increase the amount and breadth of value available to the automatic chooser.",
    ],
    strength: "Maintains high engine velocity without stopping large openings for repeated decisions.",
    watchout: "Automation sacrifices precise boon timing, and Luxquest overlaps Autopilot’s built-in enhancement rather than creating a new lane.",
    caseOrder: ["lastarchive-34", "marquee-41", "marquee-19", "marquee-28", "lastarchive-13", "tideworks-35"],
    cards: [
      { id: "lastarchive-34", role: "ENGINE", note: "Automatically chooses and enhances every Discover." },
      { id: "marquee-41", role: "PACK SOURCE", note: "Guarantees an automatic choice every time a pack opens." },
      { id: "marquee-19", role: "MARK SOURCE", note: "Marked reveals create more automatic choices." },
      { id: "marquee-28", role: "RARITY SOURCE", note: "Premium reveals create more automatic choices." },
      { id: "lastarchive-13", role: "MULTIPLIER", note: "Keeps another option from each automatic Discover." },
      { id: "tideworks-35", role: "BREADTH", note: "Gives the automatic chooser access to all five boons." },
      { id: "forgeline-01", role: "FLEX / DUPES", note: "Duplicate streaks feed hands-free Discover." },
      { id: "forgeline-11", role: "FLEX / FUSION", note: "Fusion volume feeds hands-free Discover." },
    ],
  },
  rewrite: {
    title: "Edition Sprint",
    archetype: "Binder completion / prestige speed",
    thesis: "Use recursive Mystery Packs and future-set bias to finish the binder, awaken Nameling, and convert the completed edition into permanent Inscriptions.",
    loop: [
      "Scrapactus turns duplicate sales into Salvage; Salvoon and Reclaimotive multiply the Mystery Packs produced.",
      "Futurwake and Futureword bias Mystery pulls toward cards outside normal progression while Pacturion opens future-set pack access.",
      "Rootpack turns each Mystery opening back into a loose pack until Nameling awakens and Rewrite banks the edition’s Inscriptions.",
    ],
    strength: "Every slot is aimed at unique-card velocity rather than short-term cash, which is the correct endgame objective.",
    watchout: "Rewrite resets binder, cash, and shop. Review the earned Inscriptions and display Nameling before confirming to maximize the permanent return.",
    caseOrder: ["tideworks-01", "tideworks-07", "tideworks-11", "lastarchive-38", "marquee-29", "forgeline-35"],
    cards: [
      { id: "tideworks-01", role: "IGNITION", note: "Duplicate sales begin the Salvage chain." },
      { id: "tideworks-07", role: "MULTIPLIER", note: "Every Salvage creates another Mystery Pack." },
      { id: "tideworks-11", role: "REPEAT", note: "Salvage can repeat immediately." },
      { id: "lastarchive-38", role: "FUTURE BIAS", note: "Strongly raises the chance of locked-set cards in Mystery Packs." },
      { id: "marquee-29", role: "FUTURE ACCESS", note: "Legendary pulls award packs from sets beyond normal progression." },
      { id: "forgeline-35", role: "LOOP", note: "Every Mystery Pack awards another loose pack." },
      { id: "tideworks-15", role: "FLEX / FUTURE", note: "Adds another future-card bias source." },
      { id: "lastarchive-48", role: "FINALE", note: "Awakens at completion and unlocks the Rewrite itself." },
    ],
  },
};

const SCRAP_SALVAGE_SET = {
  id: "salvage-scrap",
  index: "04B",
  name: "Salvage / Scrap",
  kicker: "Alternate design",
  summary: "Permanently destroy an owned card and turn its torn remains into a spendable resource.",
  proposal: true,
  variantOf: "salvage",
  title: "Scrapyard Economy",
  archetype: "Destructive card conversion / triggered payoff resource",
  thesis: "Salvage deletes a real card from the binder, turns its rarity into Scrap, and lets displayed cards offer optional Scrap-powered payoffs when their triggers fire.",
  resourceRules: [
    {
      label: "SALVAGE",
      text: "Choose an owned card and permanently delete one copy. Deleting your last copy requires confirmation.",
    },
    {
      label: "SCRAP",
      text: "Gain 1 / 2 / 3 / 4 / 5 Scrap for a Common / Uncommon / Rare / Epic / Legendary-or-better card.",
    },
    {
      label: "PAYOFFS",
      text: "Scrap persists between packs. Spending Scrap is never a trigger: a displayed payoff first fires from its named game event, then offers its optional Scrap cost.",
    },
  ],
  loop: [
    "Feed the yard by deleting low-value duplicates, or sacrifice a scarce high-rarity card for a much larger burst of Scrap.",
    "Scrapactus automates some duplicate destruction while Salvatort and Shredscale reward quality and timing.",
    "Bank Scrap, then wait for the right payoff trigger: a duplicate sale, Salvage completion, pack opening, premium reveal, or final-card reveal.",
  ],
  strength: "Every new card now has a second value: keep it for collection progress or destroy it to accelerate the current engine.",
  watchout: "Deleting the last owned copy can undo binder completion. The confirmation, persistent counter, and visible triggered-payoff costs must make that risk unmistakable.",
  caseOrder: ["tideworks-01", "tideworks-02", "tideworks-07", "tideworks-11", "tideworks-19", "tideworks-43"],
  cards: [
    {
      id: "tideworks-01",
      role: "GENERATOR",
      note: "Turns duplicate reveals into visible automatic destruction events.",
      preview: {
        name: "Scrapactus",
        kind: "Scrapwork",
        text: "Whenever you reveal a duplicate, 25% chance to Salvage it automatically.",
        flavor: "It never sees a spare card—only tomorrow’s parts.",
      },
    },
    {
      id: "tideworks-02",
      role: "QUALITY",
      note: "Makes the painful decision to delete a premium card materially more efficient.",
      preview: {
        name: "Salvatort",
        kind: "Scrapwork",
        text: "Whenever you Salvage a Rare-or-better card, gain 2 additional Scrap.",
        flavor: "The brighter the foil, the cleaner the cut.",
      },
    },
    {
      id: "tideworks-07",
      role: "MULTIPLIER",
      note: "Rewards holding the best sacrifice until a fresh pack begins.",
      preview: {
        name: "Shredscale",
        kind: "Scrapwork",
        text: "The first card you Salvage after opening a pack creates double Scrap.",
        flavor: "One measured tear can feed an entire workbench.",
      },
    },
    {
      id: "tideworks-11",
      role: "PAYOFF / 10",
      note: "Every completed Salvage can convert the new resource into immediate card velocity.",
      preview: {
        name: "Reclaimotive",
        kind: "Scrapwork",
        text: "Whenever you finish Salvaging a card, you may spend 10 Scrap to reveal a random card.",
        flavor: "Ten ruined prints become one unopened possibility.",
      },
    },
    {
      id: "tideworks-19",
      role: "PAYOFF / 15",
      note: "The pack-opening trigger offers more cards before the opening begins, feeding future Salvage decisions.",
      preview: {
        name: "Rivetpack",
        kind: "Scrapwork",
        text: "Whenever you open a pack, you may spend 15 Scrap to add 3 random cards to that pack.",
        flavor: "Nothing stays empty once the loose pieces start to fit.",
      },
    },
    {
      id: "tideworks-43",
      role: "PAYOFF / 30",
      note: "The final-card trigger turns a completed opening into the collection-completion sink.",
      preview: {
        name: "Archive Eater",
        kind: "Scrapwork",
        text: "Whenever you reveal the final card in a pack, you may spend 30 Scrap to reveal a random card you don't own.",
        flavor: "It chews through history until it finds a missing page.",
      },
    },
    {
      id: "tideworks-09",
      role: "PAYOFF / 5",
      note: "A cheap pressure-release valve when the player needs cash more than collection velocity.",
      preview: {
        name: "Coincompactor",
        kind: "Scrapwork",
        text: "Whenever you sell a duplicate, you may spend 5 Scrap to gain cash equal to 3× the price of a loose pack.",
        flavor: "Bent corners go in. Clean currency comes out.",
      },
    },
    {
      id: "forgeline-38",
      role: "PAYOFF / 20",
      note: "A Rare-or-better reveal creates a brief quality-upgrade window for the cards still face down.",
      preview: {
        name: "Foilpress",
        kind: "Scrapwork",
        text: "Whenever you reveal a Rare-or-better card, you may spend 20 Scrap to make a random unrevealed card in that pack foil and one rarity higher.",
        flavor: "Yesterday’s cards return as tomorrow’s impossible pull.",
      },
    },
  ],
};

export const MECHANIC_MINI_SETS = MECHANICS.flatMap((mechanic) => {
  const liveSet = {
    ...mechanic,
    ...MINI_SET_DETAILS[mechanic.id],
  };
  return mechanic.id === "salvage" ? [liveSet, SCRAP_SALVAGE_SET] : [liveSet];
});

export function getMechanicMiniSet(id) {
  return MECHANIC_MINI_SETS.find((miniSet) => miniSet.id === id) || MECHANIC_MINI_SETS[0];
}
