export const MECHANICS = [
  {
    id: "reveal",
    index: "01",
    name: "Reveal",
    kicker: "Pack opening",
    summary: "Turn a physical card, hide the back at the midpoint, and land the rarity impact.",
    steps: ["Signal", "Turn", "Rarity impact"],
  },
  {
    id: "echo",
    index: "02",
    name: "Echo",
    kicker: "Reveal repeat",
    summary: "Repeat one card’s reveal effects without creating another card.",
    steps: ["Reveal", "Afterimage", "Repeat trigger"],
  },
  {
    id: "mark",
    index: "03",
    name: "Mark",
    kicker: "Pre-reveal tell",
    summary: "Place a visible star on an unrevealed card before the player turns it.",
    steps: ["Scan pack", "Assign star", "Hold until reveal"],
  },
  {
    id: "salvage",
    index: "04",
    name: "Salvage",
    kicker: "Duplicate conversion",
    summary: "Rip open a Mystery Pack and throw its cards directly into the binder.",
    steps: ["Sell duplicate", "Split pack", "File mystery cards"],
  },
  {
    id: "mimic",
    index: "05",
    name: "Mimic",
    kicker: "Unrevealed copy",
    summary: "Copy one face-down card onto another while preserving the target’s slot.",
    steps: ["Choose source", "Copy print", "Lock target"],
  },
  {
    id: "fusion",
    index: "06",
    name: "Fusion",
    kicker: "Rarity climb",
    summary: "Collapse a same-rarity pair into one card at the next available rarity.",
    steps: ["Pair cards", "Merge", "Deal upgraded card"],
  },
  {
    id: "transmute",
    index: "07",
    name: "Transmute",
    kicker: "Rarity movement",
    summary: "Move an unrevealed card toward the rarity of the card that just resolved.",
    steps: ["Read source", "Shift grade", "Reprint target"],
  },
  {
    id: "fracture",
    index: "08",
    name: "Fracture",
    kicker: "Pack spill",
    summary: "Split the current pack and deal another pack into the same reveal.",
    steps: ["Crack wrapper", "Spill six cards", "Extend reveal"],
  },
  {
    id: "catalyst",
    index: "09",
    name: "Catalyst",
    kicker: "Effect spread",
    summary: "Spread a Mark, Mimic, or Transmute from one card to another.",
    steps: ["Effect lands", "Catalyst checks", "Copy to neighbor"],
  },
  {
    id: "blueprint",
    index: "10",
    name: "Blueprint",
    kicker: "Display case copy",
    summary: "Read the exact effect in display slot one and install it in the Blueprint slot.",
    steps: ["Read slot one", "Trace rules", "Copy effect"],
  },
  {
    id: "relay",
    index: "11",
    name: "Relay",
    kicker: "Case chain",
    summary: "Pass a trigger spark to the next displayed card on the right.",
    steps: ["Card triggers", "Spark moves right", "Neighbor resolves"],
  },
  {
    id: "discover",
    index: "12",
    name: "Discover",
    kicker: "Stacked boon",
    summary: "Choose a one-shot boon, stack it, then spend it at the matching mechanic.",
    steps: ["Deal choices", "Choose boon", "Add to stack"],
  },
  {
    id: "autopilot",
    index: "13",
    name: "Autopilot",
    kicker: "Automatic Discover",
    summary: "Choose an enhanced Discover option automatically and keep the game moving.",
    steps: ["Discover fires", "Scan choices", "Auto-pick ×2"],
  },
  {
    id: "rewrite",
    index: "14",
    name: "Rewrite",
    kicker: "Final reset",
    summary: "Close the completed binder, keep permanent Inscriptions, and begin a new edition.",
    steps: ["Complete finale", "Bind inscriptions", "Reset edition"],
  },
];
